name: Generate Shop Data JSON
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # let the action push back to the repo

    steps:
      # 1) Full checkout so auto-commit works
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Node 18
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3) Install the two deps we use
      - name: Install deps
        run: npm install --no-audit --no-fund gray-matter fs-extra

      # 4) Generate public/shopData.json
      - name: Generate shopData.json
        run: node scripts/generateShopData.js

      # 5) Commit and push the new JSON (if it changed)
      - name: Commit and push shopData.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update generated shopData.json"
          file_pattern: public/shopData.json

      # 6) NOW call the Cloudflare Worker with the secret
      - name: Trigger Cloudflare Worker sync
        env:
          WORKER_URL: https://tina-firebase-inventory-sync.lcutner5274.workers.dev/github-webhook
          AUTH_TOKEN: ${{ secrets.WORKER_CALL_SECRET }} # <-- create this repo secret
        run: |
          curl -X POST "$WORKER_URL" \
               -H "X-Auth-Token: $AUTH_TOKEN" \
               -H "Content-Type: application/json" \
               -d '{}'
