# .github/workflows/generate-shopdata.yml
name: Generate Shop Data JSON
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install gray-matter yaml fs-extra

      - name: Generate shopData.json
        run: node scripts/generateShopData.js

      - name: Commit and push shopData.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update generated shopData.json"
          file_pattern: "public/shopData.json"
          branch: main
